version: '3.5'

networks:
  symfony-network:
    external: true

services:
  symfony-web:
    container_name: symfony-web
    build:
      context: ./docker/nginx
      args:
        UID: $U_ID
    ports:
      - 1000:80      
    volumes:
      - ../:/var/www
    networks:
      - symfony-network
    depends_on:
      - symfony-app

  symfony-app:
    container_name: symfony-app
    build:
      context: ./docker/php
      args:
        UID: $U_ID
    environment:
      PHP_IDE_CONFIG: serverName=Docker
      PHP_XDEBUG_ENABLED: 1
      XDEBUG_CONFIG: client_host=172.17.0.1 client_port=9005
    ports:
      - "10022:22"
    volumes:
      - ../:/var/www
      - ./docker/php/xdebug-linux.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ~/.ssh/id_rsa:/home/symfonyuser/.ssh/id_rsa
      - ./docker/authorized_keys:/root/.ssh/authorized_keys
    networks:
      - symfony-network
    depends_on:
      - symfony-db

  symfony-db:
    container_name: symfony-db
    image: mariadb:10.7.3
    ports:
      - 40000:3306
    environment:
      MYSQL_DATABASE: symfony_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --sql_mode="STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION"
    volumes:
      - symfony-db-data:/var/lib/mysql
    networks:
      - symfony-network

volumes:
  symfony-db-data:

